---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    tags: allways
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    tags: allways
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
  


- hosts: web_servers
  become: true
  tasks: 

  - name: install latest apache and php for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: copy default html file or site
    tags: apache,apache2,ubuntu
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


  - name: install apache and php for CentOS servers
    tags: apache,apache2,centos
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
 
  - name: install unzip
    package:
      name: unzip
  
  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.10.3/terraform_1.10.3_linux_386.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755 
      owner: root
      group: root


- hosts: db_servers
  become: true
  tasks: 

  - name: install mariadb package (CentOS)
    tags: db,mariadb,centos
    dnf:
      name: 
        - mariadb
      state: latest
    when: ansible_distribution =="CentOS"